apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

configMapGenerator:
- literals:
  - ENV=development
  - DEBUG=true
  name: app-config

images:
- name: goodbirdacr.azurecr.io/medical/back
  newTag: dev

patches:
- path: patch_deployment.yaml
  target:
    group: apps
    kind: Deployment
    name: back-end-deployment
    namespace: back
    version: v1