apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-end-deployment
  namespace: back
spec:
  template:
    spec:
      containers:
      - name: back-end-deployment
        image: goodbirdacr.azurecr.io/medical/back
        resources:
          limits:
            memory: "256Mi"
          requests:
            memory: "128Mi"
            